# Solutions to Chapter 6 Exercises

In [1]:
import numpy as np

## Exercise 1

Do you think `2**np.array([1,2,3])` will work?

In [2]:
# write your code  here
2**np.array([1,2,3])

array([2, 4, 8], dtype=int32)

The answer is YES. It will work due to broadcasting. So the scalar 2 will be broadcasted to an array [2,2,2] and then the element-wise rise to power happens to get the result.

## Exercise 2

Using numpy arras find the cubes of the numbers from 11 to 19.

In [4]:
# write your code here
np.arange(11,20)**3

array([1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859], dtype=int32)

## Exercise 3

Given the 3x3 matrix of numbers from 1 to 9, find the average per row.

In [6]:
matrix = np.arange(1,10).reshape(3,3)

# write your code here
matrix.mean(axis = 1)

array([2., 5., 8.])

## Exercise 4

Given the 3x3 matrix of numbers from 1 to 9, find the average per columns.

In [7]:
matrix = np.arange(1,10).reshape(3,3)

# write your code here
matrix.mean(axis = 0)

array([4., 5., 6.])

## Exercise 5

Given the 3x3 matrix of numbers from 1 to 9, find a way using slicing to select the highlighted elements in the {numref}`high-slice`.

```{figure} ../../images/7_numpy/high-slice.jpg
:alt: highlighted_slicing_illustration
:name: high-slice
:class: ch7
:align: center

Special Slicing
```

In [9]:
matrix = np.arange(1,10).reshape(3,3)

# write your code here
matrix[[[0,0], [2,2]], [[0,2],[0,2]]]

array([[1, 3],
       [7, 9]])

To better understand this, do an element-wise matching of the indices: {[0,0], [0,2], [2,0], [2,2]}. These will be the indices of the elements that will be selected.