# Readings

**Numpy** library provides the **ndarray** implementation that we are going to introduce in this chapter. **ndarray** stands for n-dimensional array. These arrays are similar to n-dimensional lists but are more memory and processing efficient and at the same time it is easier to iterate over them. In order to be able to work with **ndarray**s, we first need to import the **numpy** module. Usually, in practice when we import numpy we use the shorthand **np** in order to faster and more easily access the functionalities of the library.

In [1]:
import numpy as np

## Creating the numpy array (manually adding elements)

To create the numpy array, we use the `array()` function of the `numpy` module which thanks to our import and shorthand notation in the previous cell, we can call it as:
```python
np.array(list_name)
```
An example would be:

In [2]:
numpy_array = np.array([1,2,3,4])
numpy_array

array([1, 2, 3, 4])

Similarly, we can create a two-dimensional array by passing two lists to the function:

In [4]:
two_dim_numpy_array = np.array([[1,2,3,4], [5,6,7,8]])
two_dim_numpy_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

This notation is similar to a list of lists.

## Attributes of **numpy** arrays

### **dtype**

One of the attributes of **numpy** arrays is the **dtype**. It is used to show the data type of the elements of the array.

````{margin}
```{note}
As you can see accessing the attributes of an object is similar to calling a method on that object expect that we do not need `()` anymore.
```
````

In [5]:
numpy_array.dtype

dtype('int32')

As you can see, the elements of the `numpy_array` are integers. `32` means that each of them occupies 32 bits in memory.

### **ndim** and **shape**

The **ndim** attribute is used to find out the dimensions of a numpy array.

In [7]:
print(numpy_array.ndim)
print(two_dim_numpy_array.ndim)

1
2


As you can see, `numpy_array` has only one dimension while the `two_dim_numpy_array` has two dimensions.

In order to exactly see the dimensions we can use the **shape** attribute:

In [8]:
print(numpy_array.shape)
print(two_dim_numpy_array.shape)

(4,)
(2, 4)


For the first array, the second value in the shape tuple is missing. Usually when the value is missing it is interpreted as 1. While the second array's dimensions are 2 and 4. The first dimension in the tuple indicates the number of rows and the second dimension indicates the number of columns.

### **size** and **itemsize**

The **size** attribute is used to find out the number of elements in an array.

In [9]:
print(numpy_array.size)
print(two_dim_numpy_array.size)

4
8


In the case of two dimensional arrays, the number of elements corresponds to the product of the number of rows with the number of columns.

**itemsize** on the other hand, is used to find out the total size in bytes of each element of the array:

In [10]:
print(numpy_array.itemsize)
print(two_dim_numpy_array.itemsize)

4
4


This perfectly corresponds to what we saw earlier using the **dtype** attribute. Here each integer is 4 bytes. Since each byte contains 8 bits, in total there would be `4x8=32` bits. Hence, the type `int32` above.

### **flat**

The **flat** attribute is used to flatten a more than one dimensional array. This is useful when we want to iterate through the elements of the array using only one external **for** loop.

In [11]:
for num in numpy_array.flat:
    print(num, end=' ')

1 2 3 4 

Otherwise, we can still iterate over more than one dimensional arrays using two for loops as previously.

In [18]:
for row in two_dim_numpy_array:
    for col in row:
        print(col, end=' ')
    print()

1 2 3 4 
5 6 7 8 


## Creating arrays with custom values using built-in functions

### Filling array with 0s

To fill an array with an arbitrary number of values, we call the `zeros()` function of the `numpy` library. It receives one argument, that determines the shape of the array to be created:

In [6]:
one_dim_zeros = np.zeros(3)
two_dim_zeros = np.zeros((3, 2))
print('A=', one_dim_zeros)
print('B=', two_dim_zeros)

A= [0. 0. 0.]
B= [[0. 0.]
 [0. 0.]
 [0. 0.]]


````{margin}
```{caution}
Make sure that the dimensions you pass to `np.zeros()`, `np.ones()` and `np.fill()` are always **positive integers**. Otherwise you will get a `ValueError` as it does not make sense to allocate negative space for an array.
```
````
As you can see, if we pass an integer, a one dimensional array will be created with as many 0s as it is indicated by the integer passed as argument. If instead, we pass a tuple then a two dimensional array will be created with the first integer in the tuple being the number of rows and the second one being the number of columns.

### Filling array with 1s

Similarly as above, to create an array of ones we use the `np.ones()` function:

In [7]:
one_dim_ones = np.ones(3)
two_dim_ones = np.ones((3, 2))
print('A=', one_dim_ones)
print('B=', two_dim_ones)

A= [1. 1. 1.]
B= [[1. 1.]
 [1. 1.]
 [1. 1.]]


Similarly, two arrays were created containing only ones.

In [8]:
one_dim_ones.dtype

dtype('float64')

```{note}
Something to notice is that the elements of the array are `floating-point` numbers and *not* `integers`. You can see this via the **dtype** attribute from above as well as from the output of the print statement that removes any trailing zeros after the decimal point `(.)`.
```

### Filling array with a specific value

And to be able to fill an array with some specific values, we can use the `full()` function of the `numpy` library. Now we need to specify even the value besides the shape of the array:

In [10]:
one_dims_value = np.full(3, 5)
two_dim_value = np.full((3, 2), 5)
print('A=', one_dims_value)
print('B=', two_dim_value)

A= [5 5 5]
B= [[5 5]
 [5 5]
 [5 5]]


### Array from ranges using **arange()**

````{margin}
```{note}
To create an array from ranges you cn use two methods:
  - **arange()** - for integer arrays
  - **linspace()** - for float arrays
```
````
The **arange()** function will create a range of values based on the arguments passed. Some examples:

In [11]:
array_1 = np.arange(3)
array_2 = np.arange(3, 7)
array_3 = np.arange(3, 10, 2)

print('A=', array_1)
print('B=', array_2)
print('C=', array_3)

A= [0 1 2]
B= [3 4 5 6]
C= [3 5 7 9]


```{admonition} What happens behind the scenes?
The **arange()** function will:
 1. first calculate the space needed,
 2. will allocate it in memory, 
 3. will generate the range 
 4. then save it in the allocated space.
```

````{margin}
```{important}
You can also use the `range()` function to create a range of values and then pass it to the `array()` function, but the `arange()` function is optimized specifically for creation of arrays from ranges and thus is better in terms of performance.
```
````

As you can see, there are 3 ways to call this function.
- If you specify only one number as its argument, then an array containing all number from 0 up until but excluding the specified argument will be created.
- If you specify two numbers, then an array with the range from the first argument up until but excluding the second one will be created.
- If you specify three numbers, then an array with the range from the first argument up until but excluding the second one will be created, however the jumps are not anymore of 1 number but they will be indicated by the third argument (which in our case it is 2).

```{note}
The **arange()** function creates arrays of integers. If instead we want to create an array of floating-point numbers, then we can use the **linspace()** function. It accepts as arguments the starting floating-point number, the ending floating-point number and the size of the array in the *num* argument. Then, based on the range and size, it creates an array with equidistant elements. For example:
```

In [17]:
floating_array = np.linspace(start=2.5, stop=7.5, num=5)
print(floating_array)

[2.5  3.75 5.   6.25 7.5 ]


## Reshaping an array

Sometimes, during manipulation of data and especially when passing it to functions we would need to reshape the arrays. This is especially useful in applications that require linear algebra operations like matrix multiplications. For this reason, `numpy` provides a method called **reshape()** to be able to change the dimensions of the arrays.

In [29]:
nums = np.arange(10)
print('nums before reshaping', nums)
nums = nums.reshape((2,5))
print('nums after reshaping')
print(nums)

nums before reshaping [0 1 2 3 4 5 6 7 8 9]
nums after reshaping
[[0 1 2 3 4]
 [5 6 7 8 9]]


As you can see, the **reshape()** method receives as argument a tuple that contains the new shape of the array. This method returns a new array and *the change does not happen in place, thus the original array passed as argument will not be affected by the change, unless we reassign it*.

```{important}
The new, reshaped array has to have the same number of elements as the original one, otherwise a `ValueError` will be raised.
```

```{note}
If an array contains many elements, not all of them will be printed. In the place of missing values you will see `...`.
```

In [28]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

```{important}
Numpy **arrays** are preferred to **lists** that we saw in Chapter 5 since operations on them are faster.
```

## Arithmetic operations on arrays

### Element-wise operations

Element-wise operations means that the operation is applied to each element separately and then the result is assembled back in an array.

#### Arithmetics

For example, in order to perform element-wise multiplication we would do:

In [43]:
array_1

array([0, 1, 2])

In [42]:
array_1 * 2

array([0, 2, 4])

As you can see, each element of the array was multiplied by 2 and a new array was returned. Note that the original array remains unchanged:

In [32]:
array_1

array([0, 1, 2])

We can do the same by adding a number:

In [33]:
array_1 + 2

array([2, 3, 4])

Or by exponentiating each element:

In [39]:
array_1 ** 2

array([0, 1, 4], dtype=int32)

Or by dividing (or floor dividing //) each element:

In [35]:
array_1 / 2

array([0. , 0.5, 1. ])

In [36]:
array_1 // 2

array([0, 0, 1], dtype=int32)

```{important}
The underlying process that allows such operations to take place is called **broadcasting**. Since these operations require two arrays, the scalar is converted into an array of the same shape (by copying the element as many times as needed) and then, the operation is performed element-wise. The multiplication from above would have been written as (after broadcasting):
```

In [44]:
array_of_twos = np.full(array_1.shape, 2) # done implicitly by broadcasting
array_1 * array_of_twos

array([0, 2, 4])

But what happens if both operands are arrays? In that case the element-wise operation takes place directly. There is no need for broadcasting:

In [46]:
first_array = np.arange(1,5)
second_array = np.arange(11,15)
first_array * second_array

array([11, 24, 39, 56])

{numref}`elem-wise-mult-assign` depicts the idea of element-wise operations in the case of multiplications. All other element-wise operations follow the same logic.

```{figure} ../images/7_numpy/element_wise_mult.jpg
:alt: element_wise_multiplication_illustration
:name: elem-wise-mult-assign
:class: ch7
:align: center

Element-wise multiplication
```

#### Comparison

Comparison between an array and a number or another array happens element-wise as well. The result will be another array that will contain boolean values indicating whether the condition holds for each element or not. For example:

In [47]:
first_array < second_array

array([ True,  True,  True,  True])

In this case, `first_array` contains values `[1,2,3,4]` and `second_array` contains values `[11,12,13,14]`. Since `1 < 11`, `2 < 12`, `3 < 13` and `4 < 14`, the resulting array will contain 4 `True` values.

What happens if the two arrays do not have the same shape?

In [48]:
third_array = np.arange(3,10)
first_array < third_array

ValueError: operands could not be broadcast together with shapes (4,) (7,) 

In this case, a `ValueError` is raised indicating that the two operands of the `<` operator **must** have the same shape.

### Axis calculations

Sometimes, we might need to perform data analysis with arrays that might have more than one dimension. Numpy offers many aggregate methods that include `min()`, `max()`, `mean()`, `std()`, etc to find, in an array-wise manner the minimum, maximum, mean and standard deviation of the array values respectively. However, it is also possible that we might need to do this operations row- or column-wise. For this we can use the notion of axis. **Axis** determines on which direction we are making the calculations. In the case of 2D arrays, it takes value either 0 or 1. If `axis=0`, then the operation will be performed column-wise, meaning that for each column, the corresponding row values will be aggregated (go vertically). If on the other hand, `axis=1`, then the operation will be row-wise, this means that for each row, the corresponding column values will be aggregated (go horizontally). {numref}`axis-idea` illustrates the idea when we want to find the minimum vale:

```{figure} ../images/7_numpy/axis-idea.jpg
:alt: axis-idea_illustration
:name: axis-idea
:class: ch7
:align: center

Axis operations
```

In code, this would look like:

In [49]:
array = np.arange(1,10).reshape(3,3)
print('Minimum per row: ', array.min(axis = 1))
print('Minimum per column: ', array.min(axis = 0))

Minimum per row:  [1 4 7]
Minimum per column:  [1 2 3]


### Other functions

Most of the arithmetic operations above can be performed using already built-in function from the `numpy` library. You can find a list of the functions in the [Official Documentation of NumPy](https://numpy.org/doc/stable/reference/ufuncs.html).